import type {
  Finding,
  IssueAssessment,
  OutputFormat,
  RepoReadiness,
  Severity,
  WaveSuggestion,
} from "./types";

export interface RenderOptions {
  colors?: boolean;
  includeRaw?: boolean;
}

const ANSI = {
  red: (s: string) => `\x1b[31m${s}\x1b[39m`,
  yellow: (s: string) => `\x1b[33m${s}\x1b[39m`,
  green: (s: string) => `\x1b[32m${s}\x1b[39m`,
  cyan: (s: string) => `\x1b[36m${s}\x1b[39m`,
  dim: (s: string) => `\x1b[2m${s}\x1b[22m`,
  bold: (s: string) => `\x1b[1m${s}\x1b[22m`,
};

const SEVERITY_EMOJI: Record<Severity, string> = {
  error: "🚫",
  warning: "⚠️",
  info: "ℹ️",
};

export function renderIssueAssessment(
  assessment: IssueAssessment,
  format: OutputFormat = "markdown",
  options: RenderOptions = {},
): string {
  switch (format) {
    case "json":
      return JSON.stringify(assessment, null, 2);
    case "text":
      return renderIssueText(assessment, options);
    case "markdown":
    default:
      return renderIssueMarkdown(assessment, options);
  }
}

export function renderRepoReadiness(
  report: RepoReadiness,
  format: OutputFormat = "markdown",
  options: RenderOptions = {},
): string {
  switch (format) {
    case "json":
      return JSON.stringify(report, null, 2);
    case "text":
      return renderReadinessText(report, options);
    case "markdown":
    default:
      return renderReadinessMarkdown(report, options);
  }
}

export function renderWaveSuggestion(wave: WaveSuggestion): string {
  return `Wave complexity (suggested): ${wave.level.toUpperCase()} · ${wave.points} points · confidence ${wave.confidence}`;
}

function renderIssueMarkdown(assessment: IssueAssessment, options: RenderOptions): string {
  const lines: string[] = [];
  lines.push(`## ContriScope report`);
  lines.push(``);
  lines.push(
    `**Score:** ${scoreBadge(assessment.score)}/100 · **Verdict:** ${verdictBadge(assessment.verdict)}`,
  );
  lines.push(``);
  lines.push(`> ${assessment.summary}`);
  lines.push(``);
  lines.push(`_${assessment.reason}_`);
  lines.push(``);

  if (assessment.wave) {
    lines.push(`**${renderWaveSuggestion(assessment.wave)}**`);
    lines.push(``);
    lines.push(`_${assessment.wave.reasoning}_`);
    lines.push(``);
  }

  lines.push(`### Dimension scores`);
  lines.push(``);
  lines.push(`| Dimension | Score | Weight |`);
  lines.push(`| --- | ---: | ---: |`);
  for (const dimension of assessment.dimensions) {
    lines.push(`| ${dimension.label} | ${dimension.score}/100 | ${dimension.weight} |`);
  }
  lines.push(``);

  if (assessment.findings.length > 0) {
    lines.push(`### Findings`);
    lines.push(``);
    for (const finding of assessment.findings) {
      const icon = SEVERITY_EMOJI[finding.severity];
      lines.push(`- ${icon} **${finding.dimension} – ${finding.title}**`);
      lines.push(`  - ${finding.message}`);
      if (finding.suggestion) {
        lines.push(`  - _Suggestion:_ ${finding.suggestion}`);
      }
    }
    lines.push(``);
  } else {
    lines.push(`No findings — this issue looks ready for contributors. ✅`);
    lines.push(``);
  }

  if (options.includeRaw) {
    lines.push(`<details>`);
    lines.push(`<summary>Raw assessment (JSON)</summary>`);
    lines.push(``);
    lines.push(`\`\`\`json`);
    lines.push(JSON.stringify(assessment, null, 2));
    lines.push(`\`\`\``);
    lines.push(`</details>`);
  }

  lines.push(`---`);
  lines.push(`_Report generated by [ContriScope](https://github.com/Sorostack/contriscope)._`);
  return lines.join("\n");
}

function renderIssueText(assessment: IssueAssessment, options: RenderOptions): string {
  const c = options.colors ? ANSI : identityColors;
  const lines: string[] = [];
  lines.push(c.bold(`ContriScope report`));
  lines.push(`${scoreBadge(assessment.score)}/100 · ${verdictBadge(assessment.verdict)}`);
  lines.push(``);
  lines.push(assessment.summary);
  lines.push(assessment.reason);
  lines.push(``);

  if (assessment.wave) {
    lines.push(c.cyan(renderWaveSuggestion(assessment.wave)));
    lines.push(``);
  }

  for (const dimension of assessment.dimensions) {
    lines.push(`  ${dimension.label.padEnd(22)} ${String(dimension.score).padStart(3)}/100`);
  }
  lines.push(``);

  if (assessment.findings.length === 0) {
    lines.push(c.green("No findings — this issue looks ready for contributors."));
  } else {
    for (const finding of assessment.findings) {
      const color =
        finding.severity === "error" ? c.red : finding.severity === "warning" ? c.yellow : c.dim;
      lines.push(
        color(`[${finding.severity.toUpperCase()}] ${finding.dimension}: ${finding.title}`),
      );
      lines.push(`  ${finding.message}`);
      if (finding.suggestion) {
        lines.push(`  -> ${finding.suggestion}`);
      }
    }
  }
  return lines.join("\n");
}

function renderReadinessMarkdown(report: RepoReadiness, options: RenderOptions): string {
  const lines: string[] = [];
  lines.push(`## Repository readiness: ${report.repo.name}`);
  lines.push(``);
  lines.push(
    `**Score:** ${scoreBadge(report.score)}/100 · **Grade:** **${report.grade}** · **Issues scored:** ${report.issuesScored}/${report.issuesTotal}`,
  );
  lines.push(``);

  lines.push(`### Program readiness`);
  lines.push(``);
  lines.push(`| Program | Score | Verdict |`);
  lines.push(`| --- | ---: | --- |`);
  lines.push(
    `| Drips Wave | ${report.programs.wave.score}/100 | ${verdictBadge(report.programs.wave.verdict)} |`,
  );
  lines.push(
    `| GrantFox | ${report.programs.grantfox.score}/100 | ${verdictBadge(report.programs.grantfox.verdict)} |`,
  );
  lines.push(``);

  lines.push(`### Section scores`);
  lines.push(``);
  lines.push(`| Section | Score |`);
  lines.push(`| --- | ---: |`);
  for (const section of report.sections) {
    lines.push(`| ${section.label} | ${section.score}/100 |`);
  }
  lines.push(``);

  lines.push(`### Wave checklist`);
  lines.push(``);
  for (const item of report.programs.wave.checklist) {
    lines.push(`- ${item.met ? "✅" : "❌"} **${item.label}** — ${item.detail}`);
  }
  lines.push(``);

  lines.push(`### GrantFox checklist`);
  lines.push(``);
  for (const item of report.programs.grantfox.checklist) {
    lines.push(`- ${item.met ? "✅" : "❌"} **${item.label}** — ${item.detail}`);
  }
  lines.push(``);

  if (report.findings.length > 0) {
    lines.push(`### Top improvements`);
    lines.push(``);
    for (const finding of report.findings.slice(0, 8)) {
      lines.push(`- ${SEVERITY_EMOJI[finding.severity]} ${finding.title} — ${finding.message}`);
    }
    lines.push(``);
  }

  if (options.includeRaw) {
    lines.push(`<details>`);
    lines.push(`<summary>Raw report (JSON)</summary>`);
    lines.push(``);
    lines.push(`\`\`\`json`);
    lines.push(JSON.stringify(report, null, 2));
    lines.push(`\`\`\``);
    lines.push(`</details>`);
  }

  lines.push(`---`);
  lines.push(`_Generated by [ContriScope](https://github.com/Sorostack/contriscope)._`);
  return lines.join("\n");
}

function renderReadinessText(report: RepoReadiness, options: RenderOptions): string {
  const c = options.colors ? ANSI : identityColors;
  const lines: string[] = [];
  lines.push(c.bold(`Repository readiness: ${report.repo.name}`));
  lines.push(
    `${scoreBadge(report.score)}/100 · Grade ${report.grade} · Issues scored ${report.issuesScored}/${report.issuesTotal}`,
  );
  lines.push(``);
  lines.push(`  Drips Wave : ${report.programs.wave.score}/100 (${report.programs.wave.verdict})`);
  lines.push(
    `  GrantFox   : ${report.programs.grantfox.score}/100 (${report.programs.grantfox.verdict})`,
  );
  lines.push(``);
  for (const section of report.sections) {
    lines.push(`  ${section.label.padEnd(24)} ${String(section.score).padStart(3)}/100`);
  }
  lines.push(``);
  for (const finding of report.findings.slice(0, 8)) {
    lines.push(c.yellow(`  [${finding.severity.toUpperCase()}] ${finding.title}`));
    lines.push(`    ${finding.message}`);
  }
  return lines.join("\n");
}

function scoreBadge(score: number): string {
  if (score >= 80) {
    return `🟢 ${score}`;
  }
  if (score >= 55) {
    return `🟡 ${score}`;
  }
  return `🔴 ${score}`;
}

function verdictBadge(verdict: string): string {
  switch (verdict) {
    case "ready":
      return "✅ ready";
    case "needs-work":
      return "🟡 needs work";
    default:
      return "🔴 blocked";
  }
}

const identityColors = {
  red: (s: string) => s,
  yellow: (s: string) => s,
  green: (s: string) => s,
  cyan: (s: string) => s,
  dim: (s: string) => s,
  bold: (s: string) => s,
};
